# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommend.proto',
  package='recommend',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0frecommend.proto\x12\trecommend\"\x18\n\x08UserInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08\x43ontents\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x0bRecommender\x12:\n\x0cGetRecommend\x12\x13.recommend.UserInfo\x1a\x13.recommend.Contents\"\x00\x62\x06proto3'
)




_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='recommend.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='recommend.UserInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=54,
)


_CONTENTS = _descriptor.Descriptor(
  name='Contents',
  full_name='recommend.Contents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='recommend.Contents.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['Contents'] = _CONTENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:recommend.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

Contents = _reflection.GeneratedProtocolMessageType('Contents', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTS,
  '__module__' : 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:recommend.Contents)
  })
_sym_db.RegisterMessage(Contents)



_RECOMMENDER = _descriptor.ServiceDescriptor(
  name='Recommender',
  full_name='recommend.Recommender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=85,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecommend',
    full_name='recommend.Recommender.GetRecommend',
    index=0,
    containing_service=None,
    input_type=_USERINFO,
    output_type=_CONTENTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDER)

DESCRIPTOR.services_by_name['Recommender'] = _RECOMMENDER

# @@protoc_insertion_point(module_scope)
