# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recommend_pb2 as recommend__pb2


class RecommenderStub(object):
    """Service Definition for Recommend
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommend = channel.unary_unary(
                '/recommend.Recommender/GetRecommend',
                request_serializer=recommend__pb2.UserInfo.SerializeToString,
                response_deserializer=recommend__pb2.Contents.FromString,
                )


class RecommenderServicer(object):
    """Service Definition for Recommend
    """

    def GetRecommend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommend': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommend,
                    request_deserializer=recommend__pb2.UserInfo.FromString,
                    response_serializer=recommend__pb2.Contents.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommend.Recommender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recommender(object):
    """Service Definition for Recommend
    """

    @staticmethod
    def GetRecommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recommend.Recommender/GetRecommend',
            recommend__pb2.UserInfo.SerializeToString,
            recommend__pb2.Contents.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
